### ISSUE TITLE
Código

### ISSUE THREAD

**Issue by Cat1546** [jota-de/mpp#3]
¡Hola!, me ha parecido muy interesante tu código y me gustaría hablar más sobre él. ¿Podrías compartirme tu correo para continuar la conversación?

**Comment by jdsr1** [comment]
Hola.
Al clonar este repositorio puedes utilizar _git log_ para ver los últimos _commits_ que hice. Ahí puedes encontrar mi correo.

**Comment by Cat1546** [comment]
No lo encuentro me podrías pasar tu correo por favor

**Comment by jdsr1** [comment]
diego_sr92@yahoo.com
Listo.
